
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[0]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[1]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[2]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[3]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[4]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[5]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[6]}]
set_property MARK_DEBUG false [get_nets {fe_spi/clk_cnt[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ps_pl/reg_o[latch_reset][data][data]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets dbg_OBUF[1]]
