create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list waveform_clk_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {wvfm_fifo/wvfm_data[0]} {wvfm_fifo/wvfm_data[1]} {wvfm_fifo/wvfm_data[2]} {wvfm_fifo/wvfm_data[3]} {wvfm_fifo/wvfm_data[4]} {wvfm_fifo/wvfm_data[5]} {wvfm_fifo/wvfm_data[6]} {wvfm_fifo/wvfm_data[7]} {wvfm_fifo/wvfm_data[8]} {wvfm_fifo/wvfm_data[9]} {wvfm_fifo/wvfm_data[10]} {wvfm_fifo/wvfm_data[11]} {wvfm_fifo/wvfm_data[12]} {wvfm_fifo/wvfm_data[13]} {wvfm_fifo/wvfm_data[14]} {wvfm_fifo/wvfm_data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {wvfm_fifo/fifo_din[0]} {wvfm_fifo/fifo_din[1]} {wvfm_fifo/fifo_din[2]} {wvfm_fifo/fifo_din[3]} {wvfm_fifo/fifo_din[4]} {wvfm_fifo/fifo_din[5]} {wvfm_fifo/fifo_din[6]} {wvfm_fifo/fifo_din[7]} {wvfm_fifo/fifo_din[8]} {wvfm_fifo/fifo_din[9]} {wvfm_fifo/fifo_din[10]} {wvfm_fifo/fifo_din[11]} {wvfm_fifo/fifo_din[12]} {wvfm_fifo/fifo_din[13]} {wvfm_fifo/fifo_din[14]} {wvfm_fifo/fifo_din[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list wvfm_fifo/fifo_wren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list wvfm_fifo/wvfm_enb]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list sys/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {wvfm_fifo/reg_i[fifo_dout][0]} {wvfm_fifo/reg_i[fifo_dout][1]} {wvfm_fifo/reg_i[fifo_dout][2]} {wvfm_fifo/reg_i[fifo_dout][3]} {wvfm_fifo/reg_i[fifo_dout][4]} {wvfm_fifo/reg_i[fifo_dout][5]} {wvfm_fifo/reg_i[fifo_dout][6]} {wvfm_fifo/reg_i[fifo_dout][7]} {wvfm_fifo/reg_i[fifo_dout][8]} {wvfm_fifo/reg_i[fifo_dout][9]} {wvfm_fifo/reg_i[fifo_dout][10]} {wvfm_fifo/reg_i[fifo_dout][11]} {wvfm_fifo/reg_i[fifo_dout][12]} {wvfm_fifo/reg_i[fifo_dout][13]} {wvfm_fifo/reg_i[fifo_dout][14]} {wvfm_fifo/reg_i[fifo_dout][15]} {wvfm_fifo/reg_i[fifo_dout][16]} {wvfm_fifo/reg_i[fifo_dout][17]} {wvfm_fifo/reg_i[fifo_dout][18]} {wvfm_fifo/reg_i[fifo_dout][19]} {wvfm_fifo/reg_i[fifo_dout][20]} {wvfm_fifo/reg_i[fifo_dout][21]} {wvfm_fifo/reg_i[fifo_dout][22]} {wvfm_fifo/reg_i[fifo_dout][23]} {wvfm_fifo/reg_i[fifo_dout][24]} {wvfm_fifo/reg_i[fifo_dout][25]} {wvfm_fifo/reg_i[fifo_dout][26]} {wvfm_fifo/reg_i[fifo_dout][27]} {wvfm_fifo/reg_i[fifo_dout][28]} {wvfm_fifo/reg_i[fifo_dout][29]} {wvfm_fifo/reg_i[fifo_dout][30]} {wvfm_fifo/reg_i[fifo_dout][31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 16 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {wvfm_fifo/reg_i[fifo_rdcnt][0]} {wvfm_fifo/reg_i[fifo_rdcnt][1]} {wvfm_fifo/reg_i[fifo_rdcnt][2]} {wvfm_fifo/reg_i[fifo_rdcnt][3]} {wvfm_fifo/reg_i[fifo_rdcnt][4]} {wvfm_fifo/reg_i[fifo_rdcnt][5]} {wvfm_fifo/reg_i[fifo_rdcnt][6]} {wvfm_fifo/reg_i[fifo_rdcnt][7]} {wvfm_fifo/reg_i[fifo_rdcnt][8]} {wvfm_fifo/reg_i[fifo_rdcnt][9]} {wvfm_fifo/reg_i[fifo_rdcnt][10]} {wvfm_fifo/reg_i[fifo_rdcnt][11]} {wvfm_fifo/reg_i[fifo_rdcnt][12]} {wvfm_fifo/reg_i[fifo_rdcnt][13]} {wvfm_fifo/reg_i[fifo_rdcnt][14]} {wvfm_fifo/reg_i[fifo_rdcnt][15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list wvfm_fifo/fifo_rdstr_fe]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {wvfm_fifo/reg_o[fifo_enb]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {wvfm_fifo/reg_o[fifo_rdstr]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {wvfm_fifo/reg_o[fifo_rst]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets dbg_OBUF[0]]
